version: '3.5'

services:
  rasa:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.rasa
    container_name: rasa
    hostname: rasa
    ports:
      - "5045"
    # depends_on:
    #   - mongo
    command: ["run", "-m", "/app/models", "--enable-api", "--cors", "*", "--port", "5045", "--debug"]
    volumes:
      - ".:/app"
    networks:
      rasanetwork:
        ipv4_address: 172.21.2.37

# Python SDK for the development of custom actions for Rasa.
  action_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.action_server
    container_name: action_server
    hostname: action_server
    ports:
      - "5055"
    depends_on:
      - rasa
    command: ["start", "--actions", "actions", "--port", "5055"]
    volumes:
      - "./actions:/app/actions"
    networks:
      rasanetwork:
        ipv4_address: 172.21.2.38

# Python script to recognize the voice and parse it to text to send it to the rasa api
  # speechToText: 
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.speechTotext
  #   container_name: speechToText
  #   hostname: speechToText
  #   ports:
  #     - "5056"
  #   depends_on:
  #     - action_server
  #   volumes:
  #     - "./speechToText:/"
  #   networks:
  #     rasanetwork:
  #       ipv4_address: 172.21.2.39

# MongoDB 
  # mongo:
  #   image: "mongo:3.7-jessie"
  #   container_name: "mongo"
  #   expose:
  #     - "27017"
  #   volumes:
  #     - ./mongo:/data/db

# Duckling is a Haskell library that parses text into structured data.
# image: rasa/duckling:latest
  # duckling:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.duckling
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     rasanetwork:
  #       ipv4_address: 172.21.2.40

networks:
  rasanetwork:
    ipam:
      config:
        - subnet: 172.21.2.0/24

volumes:
  rasa: ~
  action_server: ~