# ---
# Rasa actions server
# ---

# Extend the official Rasa SDK image
FROM rasa/rasa-sdk:undefined

# Use subdirectory as working directory
WORKDIR /app

# Copy any additional custom requirements, if necessary (uncomment next line)
# COPY actions/requirements-actions.txt ./

# Change back to root user to install dependencies
USER root

# Install extra requirements for actions code, if necessary (uncomment next line)
# RUN pip install -r requirements-actions.txt

# Copy actions folder to working directory
COPY ./actions /app/actions

RUN groupadd admin -g 11000 && \
	groupadd control -g 11001 && \ 
	groupadd operation -g 11004 && \ 
	useradd -g control -G admin -u 11000 rasadmin && \ 
	useradd -g control -G operation -l -u 1357803652 dgonzalez

# By best practices, don't run the code with root user
USER dgonzalez